NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/black.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/delete.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/errorBackground.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/errorText.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group1.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group2.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group3.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group4.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/hint.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/inputBlack.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/listSelectedBlack.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/mainBlue.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/matchButton.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/modalBackground.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/modalButton.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/step.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/unselectedOption.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/white.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Constants/Color.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
🌱 작업한 브랜치
- feature/#17
🌱 작업한 내용
- Colors.xassets 생성
- Color Catalog 추가
- SwiftGen 사용해서 Enum 객체 생성
|설명|스크린샷|
|:--:|:--:|
|가이드|<img width="834" alt="스크린샷 2021-10-01 오후 2 33 45" src="https://user-images.githubusercontent.com/69389288/135570492-8acc85d7-1b09-48ab-af6c-08429d54ad04.png">|
|컬러 변수명|<img width="677" alt="스크린샷 2021-10-01 오후 2 36 15" src="https://user-images.githubusercontent.com/69389288/135570698-be90dcf9-7082-4a9f-ad16-d6f9822b1d5f.png">|
|사용법|<img width="632" alt="스크린샷 2021-10-01 오후 2 37 42" src="https://user-images.githubusercontent.com/69389288/135570843-60c9f538-336f-4f29-9af4-ce70611dd05f.png">|
- Resolved: #17
=> [#17] - 컬러 에셋 추가

NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Resouces/Extensions/UIAlertController+Extension.swift, NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
🌱 작업한 브랜치
- feature/#20
🌱 작업한 내용
- Alert 함수 추가
- 커스텀 디자인을 위한 Extension 추가
- Swipe Action과 연결
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 12 mini - 2021-10-01 at 15 49 10](https://user-images.githubusercontent.com/69389288/135578044-9110024d-c62a-4e6d-8dfd-1b0a264a5c93.gif)|
- Resolved: #20
=> [#20] - 명함 리스트뷰 Alert창 구현 & 연결

NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Resouces/Constants/Xib.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.swift, NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift, NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.xib, NADA-iOS-forRelease/Sources/Cells/CreationCard/Background/BackgroundCollectionViewCell.swift, NADA-iOS-forRelease/Sources/Cells/CreationCard/Background/BackgroundCollectionViewCell.xib, NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift, NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.xib, NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCollectionViewCell.swift, NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCollectionViewCell.xib, NADA-iOS-forRelease/Sources/SceneDelegate.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
🌱 작업한 브랜치
- feature/#22
🌱 작업한 내용
- 메서드명 prefix 를 'init' 으로 수정
- 셀마다 nib() 메서드 생성
- Xib 구조체 만들어서 상수로 identifier 다룸
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #22
=> [#22] initializer 메서드 컨밴션에 맞춰 네이밍 변경 및 cell 리펙토링

.swiftlint.yml, NADA-iOS-forRelease/Resouces/Constants/Notification.swift, NADA-iOS-forRelease/Resouces/Storyboards/CardList.storyboard, NADA-iOS-forRelease/Resouces/Storyboards/CustomTabBar.storyboard, NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard, NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.swift, NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.xib, NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CustomTabBar/CustomTabBarController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- feature/#47
🌱 작업한 내용
- 리스트뷰에서는 탭바가 보이지 않도록 수정 -> 일단 지금은 필요없긴 한데 이미 만들어 놓은거니깐..
- 백 스와이프 제스처로 pop하는 기능 구현 
- Drag & Drop으로 cell을 정렬하는 기능 구현 -> 가장 중요한 부분!
- 테이블뷰 셀 구분선 수정
- 핀 고정시 해당 셀의 배경색이 같이 변하도록 수정
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 12 mini - 2021-10-31 at 00 11 23](https://user-images.githubusercontent.com/69389288/139538874-4cbd5af7-3605-4f48-912a-7e6a1778d233.gif) |
- Resolved: #47
=> [FEAT] #47 - 리스트뷰 세부 기능 수정과 추가 

NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Sources/NetworkModel/User/UserWithTokenRequest.swift, NADA-iOS-forRelease/Sources/NetworkModel/User/Users.swift, NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift, NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift, NADA-iOS-forRelease/Sources/SceneDelegate.swift, NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
🌱 작업한 브랜치
- feature/#63
🌱 작업한 내용
- [GET] 소셜 로그인_jwt 서버통신 파일 구현까지만 완료 -> 나중에 서버 처리 이후 이슈파서 진행
- [POST] 회원가입 서버통신 구현 & 체크 완료
- [DELETE] 회원탈퇴 서버통신 구현 & 체크 완료
- Resolved: #63
=> [FEAT] #63 - 회원 관련 추가 서버 구축

NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Sources/NetworkModel/Group/CardAddInGroupRequest.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/CardListRequest.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/GroupAddRequest.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/GroupEditRequest.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/Groups.swift, NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift, NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
🌱 작업한 브랜치
- feature/#56 
🌱 작업한 내용
- 그룹 리스트 조회 서버통신
- 그룹 속 명함 조회 서버통신
- 그룹 삭제 서버통신
- 그룹명 수정 서버통신
- 그룹명 추가 서버통신
- 명함 검색 서버통신
- 그룹 속 명함 추가 서버통신
- Resolved: #56
=> [FEAT] #56 - 명함 그룹 뷰 서버통신

NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/CardAddInGroupRequest.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/GroupAddRequest.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/GroupEditRequest.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/Groups.swift, NADA-iOS-forRelease/Sources/NetworkModel/User/User.swift
🌱 작업한 브랜치
- feature/#61
🌱 작업한 내용
- 옵셔널 변수가 필요한 경우 수정
- key-value 가 서버에서 넘어오지 않을 경우 기본값 설정.(예외처리)
> - 예외처리를 위해서 모든 변수를 옵셔널 변수로 선언하게 되면 옵셔널체이닝을 통해서 사용하는것은 문제가 안되지만 코드적으로 이 변수는 있을수도 없을수도 있는 값이 아니라 있어야하는 값인데 옵셔널로 선언하는 것이 아니라고 생각을 했습니당
> - key-value 가 넘어오지 않는 경우는 옵셔널 변수는 try? 문으로 디코딩을 먼저해서 nil 값을 할당하거나 옵셔널 변수가 아닌경우는 -1, "" 와 같이 기본값을 할당해주었습니다.
- Resolved: #61
=> [REFACTOR] #61 - NetworkModel 옵셔널변수 설정 및 예외처리

NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift, NADA-iOS-forRelease/Resouces/Constants/ViewController.swift, NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreationPreview.storyboard, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib, NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift, NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift, NADA-iOS-forRelease/Sources/SceneDelegate.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- feature/#73
🌱 작업한 내용
- 명함생성 미리보기 뷰 구현
- FrontCardCell 뷰 구현
- 제스쳐는 등록 아직 안함
|기능|스크린샷|
|:--:|:--:|
|미리보기 뷰|<img src="https://user-images.githubusercontent.com/69136340/143366536-790f1432-eee3-4f95-9d04-5b8f685e3012.png" width ="200">|
|frontCardCell|<img src="https://user-images.githubusercontent.com/69136340/143366826-6422ce47-6a08-4e62-bcd7-5311f18657be.png" width ="200">|
- Resolved: #73
=> [FEAT] #73 - 명함생성 미리보기 뷰 만들기

NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/quaternary.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/secondary.colorset/Contents.json, NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift, NADA-iOS-forRelease/Resouces/Storyboards/Group/GroupEdit.storyboard, NADA-iOS-forRelease/Resouces/Storyboards/More/More.storyboard, NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib, NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib, NADA-iOS-forRelease/Sources/Cells/GroupEdit/GroupEditTableViewCell.xib, NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.swift, NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.xib, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
🌱 작업한 브랜치
- feature/#89
🌱 작업한 내용
⭐️카드 뒷면 셀
- 현규쌤 요청 -> BackCardCell, initCell 수정 (bool형으로 받아서, 메서드에서 처리하는 방식)
- 현규 쌤 PR 답변 부분 -> 미리보기 뷰 부분 맞춰서 수정
- Bundle 빠져있는 내용들 추가
⭐️바텀시트
- 표출 시간 delay 이슈 해결
- 다크 모드 적용
⭐️기타
- 더보기 뷰 구분선 색상 수정
- 이준쌤 명함 모음 뷰 명함 글씨 색 -> background에서 .white로 변경
- 뒷면셀 수정하면서, 현규쌤 앞면셀 모서리 redius 20으로 변경했습니다!
- 그룹 편집뷰 push로 넘어왔을 때, 탭바 안보이도록 변경
- 탭바 border line과 shadow 연구
- 앞면 더미 데이터 '그'에서 '천디'로 변경
|기능|스크린샷|설명|
|:--:|:--:|:--:|
|GIF|![Simulator-Screen-Recording-iPhone-12-mini-2021-11-28-at-16 36 50](https://user-images.githubusercontent.com/69389288/143734028-ae0c00b0-2f54-4066-bd4a-72895e3b78f0.gif)| 바텀 시트를 present할 때는 바텀시트 자체 animation이 적용되기 때문에, <p> present animated는 false로 해야 지연없이 바텀시트가 표출되었습니다!! 바텀시트 올릴 때, 참고해주셔요 ^_^  <p> + 그룹에서 사용되는 present는 일괄적으로 수정했습니다!|
- Resolved: #89
=> [FIX] #89 - 카드 셀 뒷면 수정 & bottomSheet 수정

NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- feature/#107
🌱 작업한 내용
- 링크, 인스타 이미지 크기 고정
- 두줄, 말줄임 테스트용 더미데이터 설정 및 구현 확인
#109 참조
- Resolved: #107
=> [FIX] #107 - FrontCardCell 레이아웃 수정

NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift, NADA-iOS-forRelease/Sources/SceneDelegate.swift, NADA-iOS-forRelease/Sources/ViewControllers/Onboarding/OnboardingViewController.swift
🌱 작업한 브랜치
- feature/#124
🌱 작업한 내용
- 온보딩 qa 를 거친 확정
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src ="https://user-images.githubusercontent.com/69136340/145528110-4e04e2b6-a002-42ca-a287-56e4910fe9c6.mp4" width ="250">|
- Resolved: #124
=> [FIX] #124 - 온보딩 카드 간격, 바운스 수정

NADA-iOS-forRelease/Info.plist, NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- feature/#118
🌱 작업한 내용
- 인스타 앱, 사파리 링크 연결
- 인스타 없을 시 사파리로 연결
- Resolved: #118
=> [FEAT] #118 - FrontCardCell 에서 인스타 앱, 링크 사파리 연결

NADA-iOS-forRelease/Resouces/Constants/Notification.swift, NADA-iOS-forRelease/Resouces/Constants/Xib.swift, NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard, NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.xib, NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
- 메인에서 카드셀 좌우 스와이프
🌱 작업한 브랜치
- feature/#133
🌱 작업한 내용
- 초반에 작게 표현된건 MainCardCell xib 의 frame 을 작게 설정해서 그랬다 -> 327*540 으로 설정
> UICollectionView 의 사이즈를 설정하는 그런 flowlayout 역할이 없었기 때문에.
- 카드 사이즈 설정 = 높이는  topinset 과 cardspacing 과 visible next card height 를, 너비는 side inset을  포함한 크기
> 거기까지 고려해서 `return CGSize(width: 375, height: 630)` 이렇게 설정
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src ="https://user-images.githubusercontent.com/69136340/145615742-4d9c3335-841d-4c05-9ec6-c43019bdf05c.mp4" width ="250">|
- Resolved: #133
=> [FIX] #133 - 메인에서 카드셀 좌우 스와이프로 바꾸기 구현

.swiftlint.yml, NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Resouces/Constants/ViewController.swift, NADA-iOS-forRelease/Sources/Cells/GroupEdit/GroupEditTableViewCell.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardHarmonyViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
🌱 작업한 브랜치
- feature/#142
🌱 작업한 내용
- 그룹 편집 뷰, cell 라벨 클릭했을때 인식되도록 변경
- 그룹명 변경 바텀시트 추가 -> Const에도 추가
- 바텀 시트 데이터 전달되어서 텍스트 필드에는 값 포함되어 있는 상태로 표출
- 기타 SwiftLint 워닝 해결
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator-Screen-Recording-iPhone-12-mini-2021-12-12-at-20 47 34](https://user-images.githubusercontent.com/69389288/145710933-6d4bc5cb-774a-491b-ba6a-d76cf18687a7.gif)|
- Resolved: #142
=> [FEAT] #142 - 그룹명 변경 기능 구현

NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/TeamNADA/TeamNADAViewController.swift
🌱 작업한 브랜치
- feature/#145
🌱 작업한 내용
- 메인 flip 속도 변경 1 -> 0.5
- 사용하지 않는 `setUI()` 메서드 삭제
- 명함 메인뷰 공유하기 보이게 하기
- 팀나다뷰 공유하기 hidden
- 명함 상세뷰 공유하기 hidden
- 명함생성 미리보기뷰 공유하기 hidden
> 워닝이 없는 곳에서의 self 지웠습니당
|기능|스크린샷|
|:--:|:--:|
|상세보기|<img src="https://user-images.githubusercontent.com/69136340/145983215-2d934064-48a4-4bf5-9c6c-bc15b35e4733.jpeg" width="250">
|팀나다|<img src="https://user-images.githubusercontent.com/69136340/145983219-e601aaac-5b2c-4da6-b789-f01142e896e7.jpeg" width="250">
|메인|<img src="https://user-images.githubusercontent.com/69136340/145983187-cc075ba4-0ae9-4d9a-ad68-cca2c2feb552.jpeg" width="250">
- Resolved: #145
=> [FIX] #145 - 메인 flip 속도 조절 및 공유버튼 히든

NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
🌱 작업한 브랜치
- feature/#153
🌱 작업한 내용
- prepareForReuse() 오버라이드해서 subview 를 다 지워서 초기화해주었다.
- 카드크기가 contentview 로 잡아버리니까 작아져서 prepareForReuse() 에서 크기도 초기화해주었다.
> 카드가 현재 위로 올라가면 좌우 폭이 줄어드는데 이것이 초기화 되지 않는 원인으로 파악됨.
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src="https://user-images.githubusercontent.com/69136340/146048793-98f02162-0387-4d8a-a8d7-f23d0119d638.gif" width="250">|
- Resolved: #153
=> [FIX] #153 - 카드가 겹쳐보이는 버그

NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
🌱 작업한 브랜치
- feature/#152
🌱 작업한 내용
- 그룹 선택 바텀시트 수정
- QR스캔 라벨 화이트로 고정
- 명함 상세뷰 네비바 색깔 수정
- 명함 그룹 뷰 맥스 대응
|그룹선택 바텀시트 수정|![Simulator Screen Shot - iPhone 12 Pro Max - 2021-12-15 at 02 31 41](https://user-images.githubusercontent.com/69078056/146049942-c2c2a764-6dbf-4ac5-9943-f7d08ffa9a1d.png)|명함 그룹 뷰 맥스 대응|![Simulator Screen Shot - iPhone 12 Pro Max - 2021-12-15 at 02 30 51](https://user-images.githubusercontent.com/69078056/146049965-7c00e15c-9ea5-4b18-8149-a82c3faa31dd.png)|
|네비바 색깔 수정|![Simulator Screen Shot - iPhone 12 mini - 2021-12-15 at 02 32 41](https://user-images.githubusercontent.com/69078056/146049937-186b0e17-b2bd-4afd-a729-fca9ad5f9f74.png)|QR스캔 라벨 화이트|진짜죄송한데실기기키기가너무귀찮아요아하하하근데바꼈어요!|
- Resolved: #152
=> [FIX] #152 - 뷰 수정 한번에 처리

NADA-iOS-forRelease/Resouces/Constants/Notification.swift, NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift, NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift, NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.xib, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectMBTIBottomViewController.swift
🌱 작업한 브랜치
- feature#156
🌱 작업한 내용
- 뷰 클릭하면 키보드 다운.
- 필수 정보 체크 기능 추가.
- 필수, 옵션 정보 갱신 기능 추가.
- 이미지 피커 선택 이후 셀 셀렉트 유지
- 이미지를 선택한 직후에 뷰가 다시 등장할 때 0 인덱스를 셀렉트 하도록 함
- birth 와 mbti 텍스트필드 -> 텍스트뷰와 라벨로 구성 변경
- 텍필 -> birth, mbti 이동시에 키보드 내려가지 않던 버그 해결
- birth, mbti 수정 시 테두리 변경 추가
- 바텀시트 hideBottomSheetAndGoBack 오버라이드해서 birth,mbti 바텀시트 닫힐 때 노티보내도록 함
> 브랜치 이동해보셔서... 정말 다른 버그는 없는지 봐주십시오.. 선배륌들 그래서 스샷은 없습니다.. ㅋ.ㅋ
- Resolved: #156
=> [FIX] #156 - 명함생성뷰 버그 해결

NADA-iOS-forRelease/Resouces/Constants/Notification.swift, NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift, NADA-iOS-forRelease/Sources/SceneDelegate.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
🌱 작업한 브랜치
- feature/#158
🌱 작업한 내용
- 앱시작부분 탭바로 변경
- 미리보기 뷰에서는 guard let 구문 추가
- 이미지피커 cancel 할 때 dismiss 추가
- 명함배경을 마지막으로 선택하면 필수정보체크하지 않던 버그 해결
- 명함배경선택시 imagepicker 를 fullscreen 으로 띄워서 pagesheet 인 경우 취소를 누를때 통제가 되지만 창을 드래그해서 내릴때는 아무런 통제를 할 수 없는 부분을 해결
- imagepicker 선택 후 아무것도 선택하지 않으면 셀 디셀렉트 구현
- 커스텀 배경을 사용할 경우(defaultImageIndex 변수가 0이 될 경우)는 imagepicker 에서 사진 고른 후 / 사진 고른 후 다른 기본명함 선택했다가 다시 imagepicker 띄웠지만 취소 누른경우에도 기존에 고른 배경 적용
> 저 단단히 준비했습니다 이번엔 정말 믿어주십시오
- Resolved: #158
=> [FIX] #158 - 명함생성뷰 이미지피커 dismiss 동작 추가 

NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Info.plist
🌱 작업한 브랜치
- dlwns33/develop
🌱 작업한 내용
- 그냥 세로모드 고정 했어요 하하하하!!
- 아이패드도 해제했어요!
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #이슈번호
=> [CHORE] 세로모드 고정

NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
🌱 작업한 브랜치
- release/#162
🌱 작업한 내용
- 명함생성 미리보기뷰, 명함상세뷰 flip 속도조절
- 1.0 -> 0.5 로 변경
- Resolved: #162
=> [FIX] #162 - 명함생성 미리보기뷰, 명함상세뷰 flip 속도조절

NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Resouces/Constants/Header.swift, NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
🌱 작업한 브랜치
- release/#164
🌱 작업한 내용
- bearer token 지금은 그냥 테스트 토큰 값으로 넣어뒀어요! 주석으로 userdefault 토큰 값 넣어진 것도 추가해뒀습니다
- "Cotent-Type" : "application/json" 필요없는 버전은 그냥 Constant.header.bearerHeader 부르시면 됩니다!
- Group Service에 혹시 몰라서 민재꺼는 안건드려놨어용!
|기능|스크린샷|
|:--:|:--:|
|GroupService|![image](https://user-images.githubusercontent.com/69078056/146515368-08558c51-1e91-4452-a730-3a526698fd57.png)|
|Constant|![image](https://user-images.githubusercontent.com/69078056/146514764-23eadaf1-9e49-4dc2-8541-f084be09ff7c.png)|
- Resolved: #164
=> [FEAT] #164 - bearer token constant 화

NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreationPreview.storyboard, NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift, NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
🌱 작업한 브랜치
- release1.0/#171
🌱 작업한 내용
- 명함생성 미리보기 뷰 안내문구 추가
- bearer 토큰 추가 및 userId 사용하지 않아서 삭제
|기능|스크린샷|
|:--:|:--:|
|문구추가|<img src="https://user-images.githubusercontent.com/69136340/146734539-ff643937-7fed-4e07-a476-0c440b04c1c7.jpeg" width ="250">|
- Resolved: #171
=> [FIX] #171 - 명함생성 미리보기 뷰 안내문구 추가 및 서버 service 에 토큰 추가

NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
🌱 작업한 브랜치
- release/#174
🌱 작업한 내용
- 리스트 뷰 명함 삭제 시 문구 추가
- 더보기 뷰 로그아웃 클릭 시 '알림' 워딩 삭제
|리스트|![Simulator Screen Shot - iPhone 12 mini - 2021-12-20 at 17 56 06](https://user-images.githubusercontent.com/69389288/146740905-8d11376e-e94d-4ed7-bc96-e5922229534b.png)|로그아웃|![Simulator Screen Shot - iPhone 12 mini - 2021-12-20 at 17 53 52](https://user-images.githubusercontent.com/69389288/146740706-7252ca55-885f-4805-a74c-51717b347a44.png)|
- Resolved: #174
=> [FIX] #174 - 알림창 문구 수정 (리스트, 로그아웃 뷰)

NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
🌱 작업한 브랜치
- release1.0/#176
🌱 작업한 내용
- prefix 확인 후 https:// 추가
|기능|스크린샷|
|:--:|:--:|
|주소입력|<img src="https://user-images.githubusercontent.com/69136340/146875374-05b1bab7-e5a1-4999-80e4-c6ed6c31f095.png" width ="250">|
|네이버접속|<img src="https://user-images.githubusercontent.com/69136340/146875427-10f1fee1-c624-46f6-bc5b-f7619022d985.png" width ="250">|
- Resolved: #176
=> [FIX] #176 - 명함 앞면 뷰 URL 앞에 https:// 체크

NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib, NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
🌱 작업한 브랜치
- release1.0/#177
🌱 작업한 내용
- 앞면 인스타그램 미입력 시 아이콘 히든
- 앞면 링크 라벨 정중앙 위치
- 뒷면 글머리 기호 추가
> 이 브랜치에서는 공유하기 히든이 적용되지 않았습니다.
> 일단 임의로 말머리 기호 설정해두었고 슬랙에서 얘기하고 수정하겠습니다.
> 이준이 그룹 속 카드에서도 인스타그램 미입력시 예외처리 해주어야할거같아용~
|기능|스크린샷|
|:--:|:--:|
|레이아웃 수정|<img src="https://user-images.githubusercontent.com/69136340/146878878-21047c62-894d-4ec2-9d8e-d882114e5463.png" width ="250">|
- Resolved: #177
=> [FIX] #177 - 앞면 인스타그램 미입력 시 레이아웃 수정 및 뒷면 글머리 기호 추가

NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
🌱 작업한 브랜치
- release1.0/#178
🌱 작업한 내용
- 필수가 아닌 self 제거
- 공유하기 때 사용하는 initCell() 메서드 변경
- 공유하기 버튼 히든
|기능|스크린샷|
|:--:|:--:|
|공유하기 히든|<img src="https://user-images.githubusercontent.com/69136340/146876032-26ed9d7e-09c1-4174-a0f0-84419f754067.png" width ="250">|
- Resolved: #178
=> [FIX] #178 - 명함생성 미리보기 뷰 뒷면 공유하기 버튼 히든

NADA-iOS-forRelease/Resouces/Constants/Header.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
🌱 작업한 브랜치
- release/#190
🌱 작업한 내용
- 그룹 속 명함 삭제 서버를 연결했습니다
- 삭제 뒤에는 그룹 뷰로 오게 했습니다
- 삭제 시 그룹 ID가 필요하기 때문에 따로 변수를 만들어줬습니다
- 이거 엠티뷰랑 킹피셔 적용안된 상태에서 브랜치 판거라 움짤에는 안된거처럼 보여요! 합치면 될겁니다!
|기능|스크린샷|
|:--:|:--:|
|GIF|![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/69078056/146974015-881d3f3f-fc19-40ac-9d51-2fc0aa0128f2.gif)|
- Resolved: #190
=> [FEAT] #190 - 그룹 속 명함 삭제 서버

NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreationPreview.storyboard, NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift, NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift, NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
🌱 작업한 브랜치
- release1.0/#195
🌱 작업한 내용
- 명함생성 userId 추가
- 미리보기 뷰 안내문구 행간 추가
> 간격을 몰라서 슬랙에 물어본 상황 답변 받고 추가할게욥!
- Resolved: #195
=> [FIX] #195 - 명함생성 userId 추가 및 미리보기 행간 추가

NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift, NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift, NADA-iOS-forRelease/Sources/SceneDelegate.swift, NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
🌱 작업한 브랜치
- release/#199
🌱 작업한 내용
- 토큰 재발급 서버 전달 모델 변경
- 토큰 만료 상태에 따른 분기 처리 -> 만료시 로그인뷰로, 만료x시 토큰 확인 후 로그인, 탭바 위치 결정
- Resolved: #199
=> [FEAT] #199 - SceneDelegate에서 토큰 재발급 처리 로직 구현

NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift, NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift, NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift, NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift, NADA-iOS-forRelease/Sources/Views/CardView.swift, NADA-iOS-forRelease/Sources/Views/CardView.xib
🌱 작업한 브랜치
- release/#201
🌱 작업한 내용
- ID로 명함을 검색해서 추가가 가능합니다.
- 명함을 검색해서 추가 한다면 명함 상세뷰가 띄워집니다.
- 명함 상세뷰를 dismiss 하면 자동으로 그룹 뷰가 리로드 됩니다.
- 인스타그램과 링크에 아무것도 없다면 인스타그램과 링크 아이콘이 hidden 처리 됩니다.
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #201
=> [FEAT] #201 - ID로 명함 검색해서 추가하기 서버  

NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- release1.0/#207
🌱 작업한 내용
- UserDefaults 를 활용한 첫명함 생성시에만 첫명함 알람 바텀시트 등장
> 앱을 재설치하게 되면 첫명함이 아니더라도 명함을 처음만들 때 첫명함 알람 바텀시트 등장. -> 서버의 도움이 필요할듯 일단 노션에 체크리스트 만들어두고 우선순위 미뤄뒀습니다
- Resolved: #207
=> [FIX] #207 - 첫명함 알람 바텀시트 로직 변경

NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
🌱 작업한 브랜치
- release/#214
🌱 작업한 내용
- FronCardCell, BackCardCell 분기처리를 추가 해줬습니다
- MainCardCell 에서 UIImage 를 String 타입으로 변경했습니다
- 서버에서 받아오는 이미지는 킹피셔를 통해 업데이트 해주고, 로컬에 저장되어있는 이미지는 이미지를 불러와서 업데이트 합니다!
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #214
=> [FEAT] #214 - initCell 에서 서버에서 받아오는 이미지 분기처리

NADA-iOS-forRelease/Resouces/Constants/Notification.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
🌱 작업한 브랜치
- release/#219
🌱 작업한 내용
- 명함 수정 서버를 붙였습니다
- 그룹 뷰로 돌아올때마다 미분류로 초기화 되는 문제가 있어서 selectedRow라는 변수를 추가하고 저장했습니다.
|전체화면|![Simulator Screen Shot - iPhone 12 mini - 2021-12-25 at 16 42 50](https://user-images.githubusercontent.com/69078056/147380298-5886944c-4523-4bdf-9f41-02a54455c601.png)|GIF|![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/69078056/147380799-b9804e41-4bd0-4334-a8bb-8600c6de856b.gif)|
- Resolved: #219
=> [FEAT] #219 - 명함 그룹 수정 서버

NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift, NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- release1.0/#216
🌱 작업한 내용
- 공유하기 때 QR 이미지와 명함이미지 저장을 위해서 card 데이터가 필요
-> 메인에서 mainCell 을 만들 때 card 데이터를 통째로 넘김
-> front,backCardCell 에서 공유하기 버튼이 눌리면 card 데이터를 노티피케이션으로 전송
-> 공유하기 바텀시트에서 활용 가능
> 이준선배~ userID 만 뽑아서 쓰면돼 **^^**
> 명함 이미지를 둥글게 저장하는 방법을 지금 못찾아서.. 일단 노션에 이슈 남겨뒀습니다! 근데 저장할 때 CGRect 으로 받아서 정말 이악물고 한다면 bezierpath 로 둥근 사각형을 이악물고 만드는 방법이 있을거 같은데.. 일단 다른 방법부터 찾아볼게요! 
|기능|스크린샷|
|:--:|:--:|
|저장되는앞면|<img src="https://user-images.githubusercontent.com/69136340/147386783-c2dfa9e7-e4e0-442f-a028-c9df40c6e07b.jpeg" width ="250">|
|저장되는뒷면|<img src="https://user-images.githubusercontent.com/69136340/147386782-935a1393-2ce2-4dc9-a425-16312b631f2f.jpeg" width ="250">|
- Resolved: #216
=> [FEAT] #216 - 명함 이미지 렌더링해서 앨범에 저장 구현

NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- release1.0/#230
🌱 작업한 내용
- 명함생성뷰 userID 로직 설정
- 주석지우기
- Resolved: #230
=> [REFACTOR] #230 - 명함생성뷰 userID 로직 설정

NADA-iOS-forRelease/Resouces/Constants/Header.swift, NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift, NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift, NADA-iOS-forRelease/Sources/SceneDelegate.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
🌱 작업한 브랜치
- release/#233
🌱 작업한 내용
- Const.UserDefaults -> Const.UserDefaultsKey 로 변경
- 헤더에 진짜 토큰값으로 변경
- @hyun99999 @mini-min 혹시 Const.Header로 바꾸지 않은것이 있다면 각자 Service 파일 들어가서 헤더 변경해주세요!
|Code|![image](https://user-images.githubusercontent.com/69078056/147416472-8304bf61-4dce-4512-b89a-62d24f2ae8ac.png)|Code|![image](https://user-images.githubusercontent.com/69078056/147416486-19127513-806b-478f-9195-fbef8eb5161c.png)|
- Resolved: #233
=> [FEAT] #233 - UserDefault 토큰으로 헤더 변경

NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/Views/CardView.xib
🌱 작업한 브랜치
- release/#237
🌱 작업한 내용
- 공유 뷰 갤러리 권한 설정 문구를 변경했습니다!
- 권한을 허용하지 않을 시, 설정으로 들어가게 했습니다!
- 스리슬쩍 카드뷰 이미지 비율도 바꿨습니다!
- Resolved: #237
=> [FEAT] #237 - 갤러리 권한 설정 문구

NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- release1.0/#235
🌱 작업한 내용
- 명함생성 userID 가져오기 및 메인 카드 리스트 조회 로직 변경
- Resolved: #235
=> [FIX] #235 - 명함생성 userID 가져오기 및 메인 카드 리스트 조회 로직 변경

NADA-iOS-forRelease/Resouces/Constants/Notification.swift, NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- release1.0/#247
🌱 작업한 내용
- 메인뷰 명함리스트조회 로직 변경. 노티를 사용해서 명함생성, 리스트 편집 후에만 메인이 업데이트 되도록 함
-> 다른 탭에서 메인으로 돌아올 때 원래 스크롤했던 곳으로 돌아오는 자연스러움(각 탭에 대한 뎁스가 분리됨이 느껴짐)
- 메인이 업데이트 될 때 맨위로 올라오도록 함.
-> 명함생성 후 새로만든 명함은 2번째이기 때문에 접근성이 편하고 리스트 편집 후에도 내가 핀설정한 명함을 볼 수 있는 자연스러운 플로우.
- 명함생성 url 포함시키기
용량이 너무 커서 슬랙에 올려두겠습니다
- Resolved: #247
=> [FIX] #247 - 메인뷰 명함리스트조회 로직 변경 및 명함생성 url 포함시키기

NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
🌱 작업한 브랜치
- release1.0/#249
🌱 작업한 내용
- 재설치라기 보다 로그인 후(명함이 있는 계정) 메인리스트가 보이지 않는 경우가 존재
- postUserSignUpWithAPI() 메서드에서 성공적으로 토큰들을 가져오면 메인으로 화면전환하도록 하였다
- 기존에는 카톡의 경우 이메일 애플의 경우 userIdentifier 를 가져오는 메서드와 같은 층에 선언이 되서 화면전환이 되는 경우에 토큰없이 메인으로 넘어가는 경우에 메인 명함리스트가 비워져서 로직 수정했습니당 @mini-min
- Resolved: #249
=> [FIX] #249 - 재설치 시 메인 명함리스트 비워지는 이슈

NADA-iOS-forRelease/Resouces/Constants/Notification.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
🌱 작업한 브랜치
- release1.0/#255
🌱 작업한 내용
- 명함생성 후 두번째 명함으로 이동
- 리스트편집 후 첫번째 명함으로 이동
- Resolved: #255
=> [FIX] #255 - 명함생성 후 두번째 명함으로 이동 및 리스트편집 후 첫번째 명함으로 이동

NADA-iOS-forRelease/Resouces/Constants/Const.swift, NADA-iOS-forRelease/Resouces/Constants/Header.swift, NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift, NADA-iOS-forRelease/Sources/AppDelegate.swift, NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift, NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift, NADA-iOS-forRelease/Sources/SceneDelegate.swift, NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
🌱 작업한 브랜치
- release/#253
🌱 작업한 내용
- `email` 사용 -> `oauthToken?.accessToken` 사용으로 변경
- Resolved: #253
=> [FIX] #253 - 카카오톡 로그인 post 서버 통신 시, oauthToken을 사용하도록 변경 

NADA-iOS-forRelease/Resouces/Constants/Const.swift, NADA-iOS-forRelease/Resouces/Constants/Header.swift, NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift, NADA-iOS-forRelease/Sources/AppDelegate.swift, NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift, NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift, NADA-iOS-forRelease/Sources/SceneDelegate.swift, NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
🌱 작업한 브랜치
- release/#246
🌱 작업한 내용
- basicHeader 강제 언래핑 에러가 발생해서 Const에 공통 상수로 뽑아두었습니다. -> `더 좋은 방법이 있을까요..? `일단 지난번에도 보셨겠지만, 옵셔널 바인딩은 안되는거 같더라구요...
- `UserDefaults` 추가 -> isKakao, isApple(로그인 어느 것을 선택했는지 구분하기 위함)
- 자체(애플, 카카오)적으로 연결을 끊을 시, 토큰 연결을 토대로 로그인부터 진행하도록 로직 추가 (`AppDelegate`)
- 민재 담당 `Service`도 `Const header`를 가져오는 것으로 수정
- 자동 로그인 로직과 화면전환은 `splash`에서 담당하는 것으로 변경 -> 팍하면서 화면 전환되었던 이슈 해결
- Resolved: #246
=> [FIX] #246 - 자동 로그인 버그 해결

NADA-iOS-forRelease/Resouces/Constants/Notification.swift, NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
🌱 작업한 브랜치
- release1.0/#257
🌱 작업한 내용
- prepareForReuse 로 셀 초기화
- 명함 추가, 명함큐알 추가, 명함삭제, 큐알스캔 뒤로가기, 그룹 편집 뒤로가기 시에 그룹뷰 갱신 노티 추가
- viewWillAppear 에서 구현하려했지만 컬렉션뷰 맨 위로 올리는 과정이 추가되기 위해서 노티 사용
- 무한스크롤 구현
- 현재 맨 위로 올리기 위해서 scrolltotop 메서드를 사용하는데 컬렉션뷰의 델리게이트가 먼저 실행되서 item 0 으로 이동하지 못하고 에러가 발생해서 현재 1초의 딜레이를 주고 있는데 좀 더 고민해보겠습니당
> 스켈레톤 을 통해서 1초 정도 플레이스홀더 보여주고 자연스럽게 top 으로 이동 등
- Resolved: #257
=> [FEAT] #257 - 명함 그룹뷰 인파이나이트스크롤 구현

NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
🌱 작업한 브랜치
- release1.0/#262
🌱 작업한 내용
- 명함 모음 리로드 로직 수정
- 큐알스캔 뒤로가기와 ID 추가 취소를 제외한 모든 경우에서 리로드.
> 이유는 그룹 편집 스와이프에도 리로드를 적용하기 위해서 viewWillAppear 를 사용해서입니다!
- Resolved: #262
=> [FIX] #262 - 명함 모음 리로드 로직 수정

NADA-iOS-forRelease/Info.plist, NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
🌱 작업한 브랜치
- release/#218
🌱 작업한 내용
- 그룹뷰에서 애니메이션이 풀리지 않도록 하기
- 아이디로 명함 추가했을때 없는 아이디 일때도 키보드가 내려가지 않도록 하기
- CardView 이미지 비율 수정
- 그룹이 변경되었습니다. 알러트
- 그룹 추가 후 붙어버리는 이슈 resolve
- 명함 상세 아이디 없애기
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #218
=> [FEAT] #218 - 명함 그룹 뷰 1차 버그 해결

NADA-iOS-forRelease/Resouces/Constants/Notification.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
🌱 작업한 브랜치
- release1.0/#269
🌱 작업한 내용
- R 스캔 재시작 구현
- cardResult 바텀시트 내릴때와 selectGroup 바텀시트 내릴때 재시작 노티로 구현
- Resolved: #269
=> [FEAT] #269 - QR 스캔 재시작 구현

NADA-iOS-forRelease.xcodeproj/project.pbxproj, NADA-iOS-forRelease/Resouces/Constants/Xib.swift, NADA-iOS-forRelease/Resouces/Storyboards/Group/Group.storyboard, NADA-iOS-forRelease/Sources/Cells/CardList/EmptyCardListTableViewCell.swift, NADA-iOS-forRelease/Sources/Cells/CardList/EmptyCardListTableViewCell.xib, NADA-iOS-forRelease/Sources/Cells/GroupEdit/EmptyGroupEditTableViewCell.swift, NADA-iOS-forRelease/Sources/Cells/GroupEdit/EmptyGroupEditTableViewCell.xib, NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
🌱 작업한 브랜치
- release/#267
🌱 작업한 내용
- 카드 리스트 엠티뷰 추가
- 그룹 편집 엠티뷰 추가
|리스트|![simulator_screenshot_A26F8D0B-5D87-4A56-B776-482369EEA24E](https://user-images.githubusercontent.com/69389288/147689542-9431a8ad-6908-42f0-9198-6336f6259efd.png)|그룹편집|![simulator_screenshot_CCA1DF2B-A34C-486E-B7FE-C4FDE1E696B7](https://user-images.githubusercontent.com/69389288/147689569-8a1d4779-ddc9-4c1a-a9af-a6f3ad293d8f.png)|
- Resolved: #267
=> [FEAT] #267 - 리스트, 그룹 편집 엠티뷰 추가

NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
🌱 작업한 브랜치
- release/#278
🌱 작업한 내용
- 바텀시트 뒷배경 불투명도 수정
- 바텀 시트가 올라올때 불투명도가 수정되던것을 1.0 으로 변경
- Resolved: #278
=> [FIX] #278 - 바텀시트 뒷배경 불투명도 수정

NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, Podfile, Podfile.lock
🌱 작업한 브랜치
- release1.0/#280
🌱 작업한 내용
- NVActivityIndicatorView 라이브러리 추가
- 디스패치큐를 통해서 애니메이션을 main 큐에서 실행
> startAnimating() 후에 서버통신 시작보장
- activity indicator 추가
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src="https://user-images.githubusercontent.com/69136340/147715557-b20c3612-518e-42ab-80e9-2ee6f768eba4.MP4" width ="250">|
- Resolved: #280
=> [FEAT] #280 -  명함생성 시 activity indicator 추가

NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift, NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift, Podfile, Podfile.lock
🌱 작업한 브랜치
- release1.0/#282
🌱 작업한 내용
- 명함 모음 로딩뷰 구현
- 명함 삭제 후 조회 시에 명함이 두배가 되는 버그 수정
- 명함 모음 리로드 시 탈출클로저를 활용해서 명함 상단으로 이동을 직렬적으로 처리.(서버통신 후 frontCard 가 갖춰진 상태에서 scrollToTop)
- frontcard 가 0일 경우. 즉, 명함 모음에 아무것도 없는경우에 scrollToTop 을 사용하면 0 item 을 참조할 수 없기 때문에 에러가 난다. 그래서 조건문을 달아둠.
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src="https://user-images.githubusercontent.com/69136340/147743449-976a1354-8e68-4f48-9c4a-04b66cb3d3fb.mp4" width="250">|
- Resolved: #282
=> [FEAT] #282 - 명함 모음 로딩뷰 구현 및 명함 삭제 후 조회 버그 수정

NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
🌱 작업한 브랜치
- release/#284
🌱 작업한 내용
- 카카오 개발자 페이지에서 비즈앱으로 전환하기
- 이메일 필수동의항목으로 지정
- 카카오톡 로그인 로직 post 서버, `oauthToken`에서 `email`값으로 변경
|기능|스크린샷|스크린샷|
|:--:|:--:|:--:|
|로그인 동의|![KakaoTalk_Photo_2021-12-30-23-59-40 002](https://user-images.githubusercontent.com/69389288/147762972-d4f2e891-2b3e-4778-a968-b03465429227.jpeg)|![KakaoTalk_Photo_2021-12-30-23-59-39 001](https://user-images.githubusercontent.com/69389288/147762975-c59b11ef-432e-4683-9073-f80d4cc5fae0.jpeg)|
- Resolved: #284
=> [FIX] #284 - 카카오톡 로그인 post 서버, oauthToken에서 email값으로 변경

NADA-iOS-forRelease/Info.plist
🌱 작업한 브랜치
- release/#294
🌱 작업한 내용
- 앱 언어 한국어로 변경하기위해 info.plist 변경했습니다!
|기능|스크린샷|
|:--:|:--:|
|info.plist|![image](https://user-images.githubusercontent.com/69078056/148582309-e042f63e-5483-48a0-ade7-df37ea2463ce.png)|
|이제 한국어로!|![Simulator Screen Shot - iPhone 12 mini - 2022-01-08 at 02 23 50](https://user-images.githubusercontent.com/69078056/148582426-c749964a-6588-4b4d-ba96-f9edd995a422.png)|
- Resolved: #294
=> [CHORE] #294 - 앱 언어 한국어로 변경하기

NADA-iOS-forRelease/Sources/Cells/GroupEdit/GroupEditTableViewCell.xib
🌱 작업한 브랜치
- release/#301
🌱 작업한 내용
- 그룹 편집 뷰에서는 그룹명이 라벨 길이 넘으면 `Truncate Tail`로 보여집니다.
|기능|스크린샷|
|:--:|:--:|
|GIF|![simulator_screenshot_181CCE82-D9B4-41B4-B1E5-6296F5E7AF88](https://user-images.githubusercontent.com/69389288/148587913-5c5f6b82-dc16-4022-86a3-2ac2da3f7515.png)|
- Resolved: #301
=> [FIX] #301 - 그룹 편집 뷰 그룹명 길이 제한
