TeamNADA/NADA-iOS-ForRelease

.swiftlint.yml
NADA-iOS-forRelease.xcodeproj/project.pbxproj
NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
NADA-iOS-forRelease/Sources/Cells/TempCell.swift

🌱 작업한 브랜치
- feature/#5
🌱 작업한 내용
- FrontCardCell 구현
- 뷰컨과 연결
- 임시 파일 TempCell 삭제
- swiftlint 수정(function_parameter_count) : 파라미터의 갯수 제한 해제.
- 아직 배경에 대한 설정은 안함
|기능|스크린샷|
|:--:|:--:|
|명함 앞면 구현|<img width="200" alt="스크린샷 2021-09-19 오후 11 19 17" src="https://user-images.githubusercontent.com/69136340/133930986-783aec65-2e8a-4512-b2fd-cb45d8bd77c6.png">|
- Resolved: #5

[#5] 명함 앞면 구현

---

NADA-iOS-forRelease.xcodeproj/project.pbxproj
NADA-iOS-forRelease/Sources/Group/ChangeGroupRequest.swift
NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
NADA-iOS-forRelease/Sources/NetworkModel/GenericResponse.swift
NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
NADA-iOS-forRelease/Sources/NetworkService/Plugin/MoyaLoggerPlugin.swift
NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift

🌱 작업한 브랜치
- feature/#53
🌱 작업한 내용
- CardAPI, CardService 작성
- Card 네트워크 데이터 모델 생성
- 명함생성 moya task 코드 리펙토링 필요(Card 데이터모델 공유를 위해서 우선 커밋)
- Resolved: #53

[FEAT] #53 - 명함 생성, 명함 세부 조회 서버통신

---

NADA-iOS-forRelease/Sources/SceneDelegate.swift
NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Podfile
Podfile.lock

🌱 작업한 브랜치
- feature/#57
🌱 작업한 내용
- IQKeyboardManager 라이브러리 추가
- SceneDelegate 에서 설정
- Resolved: #57

[ADD] #57 - IQKeyboardManager 라이브러리 추가 및 설정

---

NADA-iOS-forRelease.xcodeproj/project.pbxproj

🌱 작업한 브랜치
- feature/#75
- Resolved: #75

[CHORE] #75 - 폰트 다시 추가

---

NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/background.colorset/Contents.json
NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/quaternary.colorset/Contents.json
NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/secondary.colorset/Contents.json
NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/tertiary.colorset/Contents.json
NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
NADA-iOS-forRelease/Resouces/Storyboards/CardList.storyboard
NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard
NADA-iOS-forRelease/Resouces/Storyboards/More/More.storyboard
NADA-iOS-forRelease/Resouces/Storyboards/TabBar.storyboard
NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.xib
NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.xib

🌱 작업한 브랜치
- feature/#82
- Resolved: #82

[CHORE] #82 - 다크모드 대응 컬러 변경

---

NADA-iOS-forRelease/Info.plist
NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
NADA-iOS-forRelease/Resouces/Storyboards/More/More.storyboard
NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.swift
NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.xib
NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
NADA-iOS-forRelease/Sources/ViewControllers/TabBar/TabBarViewController.swift

🌱 작업한 브랜치
- feature/#91
🌱 작업한 내용
- 일단 작업했던 내용은 주석으로 TODO 처리 해두었습니다.
- 라이트, 다크 모드는 일단 시스템을 따라가도록 바꿔둔 상태입니다.
- 카카오톡 로직 먼저짜러 출발~!
- Resolved: #이슈번호

[FEAT] #91 - 다크, 라이트 모드는 일단 시스템 따라가기로

---

NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift

🌱 작업한 브랜치
- feature/#116
🌱 작업한 내용
- 웹상에서 컨플릭트 해결이 어려워 우선 머지 후 다시 작업
- Resolved: #116

[FIX] #116 - Merge branch 'develop' into feature/#116

---

NADA-iOS-forRelease/Resouces/Constants/URL.swift

🌱 작업한 브랜치
- feature/#146
- Resolved: #146

[CHORE] #146 - baseURL 수정

---

NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift

🌱 작업한 브랜치
- relsease1.0/#169
🌱 작업한 내용
- 플레이스홀더 변경
- 상태바 위치 스와이프와 글자 클릭 동일하게 변경
|기능|스크린샷|
|:--:|:--:|
|플레이스 홀더 수정|<img src="https://user-images.githubusercontent.com/69136340/146724204-3cfb8bc9-a175-4f00-b3f7-69d0157333d7.jpeg" width ="250">|
|상태바 위치 수정|<img src="https://user-images.githubusercontent.com/69136340/146734947-5e54df16-c3f0-4c45-8dc2-0e3ba0edb397.jpeg" width ="250">|
- Resolved: #169

[FIX] #169 - 명함생성뷰 플레이스홀더 변경 및 상태바 위치 조절

---

NADA-iOS-forRelease/Resouces/Constants/URL.swift
NADA-iOS-forRelease/Sources/ViewControllers/OpenSource/OpenSourceViewController.swift

🌱 작업한 브랜치
- release/#189
🌱 작업한 내용
- 더보기 - 오픈소스 라이브러리 창에 Kingfisher 링크 연결
|기능|스크린샷|
|:--:|:--:|
|창|![Simulator Screen Shot - iPhone 13 mini - 2021-12-21 at 21 45 53](https://user-images.githubusercontent.com/69389288/146932419-196a1d9f-6803-471a-a0df-32233829a3cd.png)|
- Resolved: #189

[FEAT] #189 - Kingfisher 라이브러리 오픈소스 라이브러리에 추가

---

NADA-iOS-forRelease/Resouces/Storyboards/Group/Group.storyboard
NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift

🌱 작업한 브랜치
- feature/#187 
🌱 작업한 내용
- 명함 그룹 뷰 엠티 뷰 추가
|기능|스크린샷|
|:--:|:--:|
|화면|![Simulator Screen Shot - iPhone 11 - 2021-12-21 at 21 44 54](https://user-images.githubusercontent.com/69078056/146951496-191e3a18-de57-446c-b3fe-e50ffcf63dea.png)|
- Resolved: #187

[FEAT] #187 - 명함 그룹 뷰 엠티 뷰 추가

---

NADA-iOS-forRelease/Resouces/Constants/Header.swift
NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift

🌱 작업한 브랜치
-  release/#193
🌱 작업한 내용
- 서버에서 받아오는 이미지들은 킹피셔를 적용합니다
- 로컬에 있다면 UIImage를 사용합니다
- 분기처리는 prefix 를 사용합니다
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #193

[FEAT] #193 - cardCell 이미지 분기처리

---

NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift

🌱 작업한 브랜치
- release1.0/#240
🌱 작업한 내용
- 공유하기에서 이미지 저장 시 서버에서 이미지를 가져와서 반영하는 생성자 함수 사용
- Resolved: #240

[FIX] #240 - 공유하기 이미지저장 초기화함수 변경

---

NADA-iOS-forRelease.xcodeproj/project.pbxproj

🌱 작업한 브랜치
- release/#244 
🌱 작업한 내용
- 빌드 3으로 업데이트 했습니다!
|기능|스크린샷|
|:--:|:--:|
|숫자|![image](https://user-images.githubusercontent.com/69078056/147419342-5e6db66b-73f8-4404-b7b9-79e7bd2da7bf.png)|
- Resolved: #244

[CHORE] #244 - 빌드 3으로 업데이트

---

NADA-iOS-forRelease/Resouces/Constants/Header.swift
NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift
NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift

🌱 작업한 브랜치
- release/#260
🌱 작업한 내용
- 그룹 추가시, 그룹에 바로 업데이트 되지 않는 이슈 해결
- 그룹 편집시, 그룹에 바로 업데이트 되지 않는 이슈 해결
- 그룹 삭제시, 그룹에 바로 업데이트 되지 않는 이슈 해결
- 그룹 추가된 다음 알림창 표출
- Resolved: #260

[FIX] #260 - 그룹 편집 리로드 버그 해결

---

NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift

🌱 작업한 브랜치
- release/#265
🌱 작업한 내용
- 동일한 그룹명 alert
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #265

[FEAT] #265 - 동일한 그룹명 alert

---

NADA-iOS-forRelease/Resouces/Constants/URL.swift
NADA-iOS-forRelease/Sources/ViewControllers/OpenSource/OpenSourceViewController.swift

🌱 작업한 브랜치
- release/#287
🌱 작업한 내용
- 오픈 소스 라이브러리 항목 추가
- Const에 URL 추가
|기능|스크린샷|
|:--:|:--:|
|오픈소스 라이브러리 뷰|![simulator_screenshot_F715CFA1-5FDC-4C29-AD03-E82A32DE9770](https://user-images.githubusercontent.com/69389288/147871448-21733e9b-1c0e-4e21-829c-b09f7fc303ba.png)|
- Resolved: #287

[FEAT] #287 - NVActivityIndicatorView 오픈소스 라이브러리 추가

---

NADA-iOS-forRelease/Resouces/Storyboards/Login/Login.storyboard
NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift

🌱 작업한 브랜치
- release/#291
|미니|![Simulator Screen Shot - iPhone 12 mini - 2022-01-08 at 02 09 27](https://user-images.githubusercontent.com/69389288/148580696-93cd6198-89c4-4849-8f80-03f9605cbc67.png)|프로|![Simulator Screen Shot - iPhone 13 Pro - 2022-01-08 at 02 09 28](https://user-images.githubusercontent.com/69389288/148580861-3a0a955c-5c84-4efc-bc32-271e5ed564f8.png)|
- Resolved: #291

[CHORE] #291 - 로그인 버튼 레이아웃 조정

---

NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift
NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift

🌱 작업한 브랜치
- release/#296
🌱 작업한 내용
- 온보딩 연결했습니다 ^__^
- 디테일) 교수님 부분인데,,, 제가 명함 생성 생년월일 2022년 추가했습니다 ^__^
- Resolved: #296

[FEAT] 온보딩 스플래시 뷰에 연결

---

NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift

🌱 작업한 브랜치
- release/#298
🌱 작업한 내용
- 그룹명 collection view cell 객체 생성해서 데이터를 넣고 frame 의 size 를 가져오기
- 헷갈려서 커밋은 FEAT으로 했네요 제송합니다..
|여기좀봐줘유!!|![Simulator Screen Shot - iPhone 12 mini - 2022-01-08 at 02 50 18](https://user-images.githubusercontent.com/69078056/148585588-c761e8d7-118e-42c8-b089-eadbba33564e.png)|여기도!!!|![Simulator Screen Shot - iPhone 12 mini - 2022-01-08 at 02 50 11](https://user-images.githubusercontent.com/69078056/148585597-bf34df4d-d79e-4589-9ff6-ce164e4c6dc1.png)|
- Resolved: #298

[FIX] #298 -그룹명 dynamic Cell 코드 수정

---

NADA-iOS-forRelease.xcodeproj/project.pbxproj
NADA-iOS-forRelease/Info.plist

🌱 작업한 브랜치
- release1.0.1/1
🌱 작업한 내용
- chore #307 
- Resolved: #307

[CHORE] release1.0.1/1 -> develop 머지하기

---

NADA-iOS-forRelease.xcodeproj/project.pbxproj

🌱 작업한 브랜치
- feature/#324
🌱 작업한 내용
- 버전 1.0.2로 하나 올렸습니다!
- Resolved: #324

[CHORE] #324 - 버전 1.0.2로 업데이트
